config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  get '/updating' => 'services#updating'
  get '/networking' => 'services#networking'
  get '/online_backup' => 'services#online_backup'
  get '/optimization' => 'services#optimization'
  get '/diagnosis_repair' => 'services#diagnosis_repair'
  get '/setup_install' => 'services#setup_install'
  get '/virus_removal' => 'services#virus_removal'

  resources :feedbacks

  resources :services do

      get :updating

  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  def new
  @feedback = Feedback.new
  end

  def create

    @feedback = Feedback.create(feedback_params)
    if @feedback.save
      redirect_to root_path
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :contact_no, :description)
  end

end

app/controllers/how_works_controller.rb
class HowWorksController < ApplicationController

  def how_it_works

  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def updating

  end

  def optimization

  end

  def online_backup

  end

  def networking

  end

  def diagnosis_repair

  end

  def setup_install

  end

  def virus_removal

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TechMaxwell</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => 'shared/header' %>
<%= yield %>

</body>
</html>

app/views/services/diagnosis_repair.html.erb
<!-- Start single page header -->
<section id="single-page-header">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="single-page-header-left">
            <h2>Diagnosis & Repair</h2>
            <p>Call us toll free 1 877 770 0329 for the best support experience!</p>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="single-page-header-right">
            <ol class="breadcrumb">
              <li><%= link_to 'Home', root_path,
                              :data => { :no_turbolink => true } %></li>
              <li class="active">Diagnosis & Repair</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End single page header -->

<!-- Start blog archive -->
<section id="blog-archive">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="blog-archive-area">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="blog-archive-left">
                <!-- Start blog news single -->
                <article class="blog-news-single">
                  <div class="blog-news-img" style="width: 80% !important; margin-left: 10%;">
                    <img src="/assets/diagnosis_repair.jpg" alt="image">
                  </div>
                  <div class="blog-news-title">
                    <h2>Work faster on your computers with support from Techmaxwell. Call toll free 1 877 770 0329.</h2>
                    <p>Annoying start-up error messages, trouble in staying connected to the internet and fear with window’s ‘Blue Screen Of Death’ can be solved by comprehensive diagnostic and complete repair of computer and connected devices such as printers, routers, MP3 players, and over 500 software applications.</p>
                    <!--<p>By <a class="blog-author" href="#">John Powell</a> <span class="blog-date">|18 October 2015</span></p>-->
                  </div>

                  <h1>What will you get?</h1>
                  <h3>Fix Software and Hardware Errors</h3>

                  <li>Diagnose and troubleshoot both software and hardware errors on your PCs or servers.</li>
                  <li>Ensure smooth performance.</li>

                  <h3>Resolve Compatibility Issues</h3>
                  <li>Fix conflicts and compatibility issues with software applications or hardware running on your computer.</li>
                  <h3>Reduce Computer Crashes</h3>


                  <li>Identify and fix issues causing your computer to crash often.</li>
                  <h3>Elimination of Problems at the Root</h3>
                  <li>Root cause identification</li>
                  <li>Implementing logical troubleshooting methodology to eliminate problems completely</li>
                  <li>Restrict re-occurrence</li>











                  <!--<div class="blog-news-details blog-single-details">-->
                  <!--<p>Even computers with latest & powerful generation processor and gigabytes of RAM, old files build up on your hard drive and all the adding and removing of software leaves behind quite a mess, all these factors reduce the efficiency of your computer, which means you don’t get the performance you deserve.</p>-->

                  <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of <a href="#">text</a></p>-->
                  <!--<blockquote>-->
                  <!--<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from</p>-->
                  <!--<span> - John Doe</span>-->
                  <!--</blockquote>-->
                  <!--<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text</p>-->
                  <!--<ul>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--</ul>-->
                  <!--<ol>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--<li>There are many variations of passages of Lorem Ipsum</li>-->
                  <!--</ol>-->
                  <!--<h1>This is H1 Title Example</h1>-->
                  <!--<h2>This is H2 Title Example</h2>-->
                  <!--<h3>This is H3 Title Example</h3>-->
                  <!--<h4>This is H4 Title Example</h4>-->
                  <!--<h5>This is H5 Title Example</h5>-->
                  <!--<h6>This is H6 Title Example</h6>-->
                  <!--<div class="blog-single-bottom">-->
                  <!--<div class="row">-->
                  <!--<div class="col-md-8">-->
                  <!--<div class="blog-single-tag">-->
                  <!--<span class="fa fa-tags"></span>-->
                  <!--<a href="#">Design,</a>-->
                  <!--<a href="#">Photoshop,</a>-->
                  <!--<a href="#">Development</a>-->
                  <!--</div>-->
                  <!--</div>-->
                  <!--<div class="col-md-4">-->
                  <!--<div class="blog-single-social">-->
                  <!--<a href="#"><i class="fa fa-facebook"></i></a>-->
                  <!--<a href="#"><i class="fa fa-twitter"></i></a>-->
                  <!--<a href="#"><i class="fa fa-linkedin"></i></a>-->
                  <!--<a href="#"><i class="fa fa-google-plus"></i></a>-->
                  <!--<a href="#"><i class="fa fa-pinterest"></i></a>-->
                  <!--</div>-->
                  <!--</div>-->
                  <!--</div>-->
                  <!--</div>-->
                  <!--</div>-->
                </article>
                <!-- Start blog navigation -->
                <!--<div class="blog-navigation-area">-->
                <!--<div class="blog-navigation-prev">-->
                <!--<a href="#">-->
                <!--<h5>All about writing story</h5>-->
                <!--<span>Previous Post</span>-->
                <!--</a>-->
                <!--</div>-->
                <!--<div class="blog-navigation-next">-->
                <!--<a href="#">-->
                <!--<h5>All about friends story</h5>-->
                <!--<span>Next Post</span>-->
                <!--</a>-->
                <!--</div>-->
                <!--</div>-->
                <!-- Start Comment box -->
                <!--<div class="comments-box-area">-->
                <!--<h2>Leave a Comment</h2>-->
                <!--<p>Your email address will not be published.</p>-->
                <!--<form action="" class="comments-form">-->
                <!--<div class="form-group">-->
                <!--<input type="text" class="form-control" placeholder="Your Name">-->
                <!--</div>-->
                <!--<div class="form-group">-->
                <!--<input type="email" class="form-control" placeholder="Email">-->
                <!--</div>-->
                <!--<div class="form-group">-->
                <!--<textarea placeholder="Comment" rows="3" class="form-control"></textarea>-->
                <!--</div>-->
                <!--<button class="comment-btn">Submit Comment</button>-->
                <!--</form>-->
                <!--</div>-->
              </div>
            </div>
            <div class="col-md-2"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End blog archive -->

<!-- Start subscribe us -->
<section id="subscribe">
  <div class="subscribe-overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="subscribe-area">
            <h2>Subscribe Newsletter</h2>
            <form action="" class="subscrib-form">
              <input type="text" placeholder="Enter Your E-mail..">
              <button class="subscribe-btn" type="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End subscribe us -->

<!-- Start footer -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="footer-left">
          <p>Designed by <a href="http://www.markups.io/">MarkUps.io</a></p>
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="footer-right">
          <a href="index.html"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-google-plus"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-pinterest"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/services/networking.html.erb
<!-- Start single page header -->
<section id="single-page-header">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="single-page-header-left">
            <h2>Networking</h2>
            <p>this is  networking text</p>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="single-page-header-right">
            <ol class="breadcrumb">
              <li><%= link_to 'Home', root_path,
                              :data => { :no_turbolink => true } %></li>
              <li class="active">Networking</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End single page header -->

<!-- Start blog archive -->
<section id="blog-archive">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="blog-archive-area">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="blog-archive-left">
                <!-- Start blog news single -->
                <article class="blog-news-single">
                  <div class="blog-news-img">
                    <img src="/assets/blog-img-1.jpg" alt="image">
                  </div>
                  <div class="blog-news-title">
                    <h2>All about writing story</h2>
                    <p>By <a class="blog-author" href="#">John Powell</a> <span class="blog-date">|18 October 2015</span></p>
                  </div>
                  <div class="blog-news-details blog-single-details">
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the</p>

                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of <a href="#">text</a></p>
                    <blockquote>
                      <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from</p>
                      <span> - John Doe</span>
                    </blockquote>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text</p>
                    <ul>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                    </ul>
                    <ol>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                    </ol>
                    <h1>This is H1 Title Example</h1>
                    <h2>This is H2 Title Example</h2>
                    <h3>This is H3 Title Example</h3>
                    <h4>This is H4 Title Example</h4>
                    <h5>This is H5 Title Example</h5>
                    <h6>This is H6 Title Example</h6>
                    <div class="blog-single-bottom">
                      <div class="row">
                        <div class="col-md-8">
                          <div class="blog-single-tag">
                            <span class="fa fa-tags"></span>
                            <a href="#">Design,</a>
                            <a href="#">Photoshop,</a>
                            <a href="#">Development</a>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="blog-single-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
                <!-- Start blog navigation -->
                <div class="blog-navigation-area">
                  <div class="blog-navigation-prev">
                    <a href="#">
                      <h5>All about writing story</h5>
                      <span>Previous Post</span>
                    </a>
                  </div>
                  <div class="blog-navigation-next">
                    <a href="#">
                      <h5>All about friends story</h5>
                      <span>Next Post</span>
                    </a>
                  </div>
                </div>
                <!-- Start Comment box -->
                <div class="comments-box-area">
                  <h2>Leave a Comment</h2>
                  <p>Your email address will not be published.</p>
                  <form action="" class="comments-form">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Your Name">
                    </div>
                    <div class="form-group">
                      <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                      <textarea placeholder="Comment" rows="3" class="form-control"></textarea>
                    </div>
                    <button class="comment-btn">Submit Comment</button>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-2"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End blog archive -->

<!-- Start subscribe us -->
<section id="subscribe">
  <div class="subscribe-overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="subscribe-area">
            <h2>Subscribe Newsletter</h2>
            <form action="" class="subscrib-form">
              <input type="text" placeholder="Enter Your E-mail..">
              <button class="subscribe-btn" type="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End subscribe us -->

<!-- Start footer -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="footer-left">
          <p>Designed by <a href="http://www.markups.io/">MarkUps.io</a></p>
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="footer-right">
          <a href="index.html"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-google-plus"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-pinterest"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/services/online_backup.html.erb
<!-- Start single page header -->
<section id="single-page-header">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="single-page-header-left">
            <h2>Online Backup</h2>
            <p>this is  onlline backup text</p>
          </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="single-page-header-right">
            <ol class="breadcrumb">
              <li><%= link_to 'Home', root_path,
                              :data => { :no_turbolink => true } %></li>
              <li class="active">Online Backup</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End single page header -->

<!-- Start blog archive -->
<section id="blog-archive">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="blog-archive-area">
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="blog-archive-left">
                <!-- Start blog news single -->
                <article class="blog-news-single">
                  <div class="blog-news-img">
                    <img src="/assets/blog-img-1.jpg" alt="image">
                  </div>
                  <div class="blog-news-title">
                    <h2>All about writing story</h2>
                    <p>By <a class="blog-author" href="#">John Powell</a> <span class="blog-date">|18 October 2015</span></p>
                  </div>
                  <div class="blog-news-details blog-single-details">
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the</p>

                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of <a href="#">text</a></p>
                    <blockquote>
                      <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from</p>
                      <span> - John Doe</span>
                    </blockquote>
                    <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text</p>
                    <ul>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                    </ul>
                    <ol>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                      <li>There are many variations of passages of Lorem Ipsum</li>
                    </ol>
                    <h1>This is H1 Title Example</h1>
                    <h2>This is H2 Title Example</h2>
                    <h3>This is H3 Title Example</h3>
                    <h4>This is H4 Title Example</h4>
                    <h5>This is H5 Title Example</h5>
                    <h6>This is H6 Title Example</h6>
                    <div class="blog-single-bottom">
                      <div class="row">
                        <div class="col-md-8">
                          <div class="blog-single-tag">
                            <span class="fa fa-tags"></span>
                            <a href="#">Design,</a>
                            <a href="#">Photoshop,</a>
                            <a href="#">Development</a>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="blog-single-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </article>
                <!-- Start blog navigation -->
                <div class="blog-navigation-area">
                  <div class="blog-navigation-prev">
                    <a href="#">
                      <h5>All about writing story</h5>
                      <span>Previous Post</span>
                    </a>
                  </div>
                  <div class="blog-navigation-next">
                    <a href="#">
                      <h5>All about friends story</h5>
                      <span>Next Post</span>
                    </a>
                  </div>
                </div>
                <!-- Start Comment box -->
                <div class="comments-box-area">
                  <h2>Leave a Comment</h2>
                  <p>Your email address will not be published.</p>
                  <form action="" class="comments-form">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Your Name">
                    </div>
                    <div class="form-group">
                      <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                      <textarea placeholder="Comment" rows="3" class="form-control"></textarea>
                    </div>
                    <button class="comment-btn">Submit Comment</button>
                  </form>
                </div>
              </div>
            </div>
            <div class="col-md-2"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End blog archive -->

<!-- Start subscribe us -->
<section id="subscribe">
  <div class="subscribe-overlay">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="subscribe-area">
            <h2>Subscribe Newsletter</h2>
            <form action="" class="subscrib-form">
              <input type="text" placeholder="Enter Your E-mail..">
              <button class="subscribe-btn" type="submit">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End subscribe us -->

<!-- Start footer -->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6">
        <div class="footer-left">
          <p>Designed by <a href="http://www.markups.io/">MarkUps.io</a></p>
        </div>
      </div>
      <div class="col-md-6 col-sm-6">
        <div class="footer-right">
          <a href="index.html"><i class="fa fa-facebook"></i></a>
          <a href="#"><i class="fa fa-twitter"></i></a>
          <a href="#"><i class="fa fa-google-plus"></i></a>
          <a href="#"><i class="fa fa-linkedin"></i></a>
          <a href="#"><i class="fa fa-pinterest"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>